BEGIN;

CREATE TABLE IF NOT EXISTS public.gym_free_weights (
    gym_id integer PRIMARY KEY REFERENCES public.gyms(id) ON DELETE CASCADE,
    dumbbell_min_kg integer,
    dumbbell_max_kg integer,
    dumbbell_racks integer NOT NULL DEFAULT 0,
    squat_racks integer NOT NULL DEFAULT 0,
    flat_benches integer NOT NULL DEFAULT 0,
    incline_benches integer NOT NULL DEFAULT 0,
    platforms integer NOT NULL DEFAULT 0,
    preacher_curl_stations integer NOT NULL DEFAULT 0,
    verified boolean NOT NULL DEFAULT false,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    CONSTRAINT gym_free_weights_dumbbell_min_check
        CHECK (dumbbell_min_kg IS NULL OR dumbbell_min_kg BETWEEN 0 AND 999),
    CONSTRAINT gym_free_weights_dumbbell_max_check
        CHECK (dumbbell_max_kg IS NULL OR dumbbell_max_kg BETWEEN 0 AND 999),
    CONSTRAINT gym_free_weights_dumbbell_range_check
        CHECK (dumbbell_min_kg IS NULL OR dumbbell_max_kg IS NULL OR dumbbell_max_kg >= dumbbell_min_kg),
    CONSTRAINT gym_free_weights_counts_check
        CHECK (
            dumbbell_racks BETWEEN 0 AND 999
            AND squat_racks BETWEEN 0 AND 999
            AND flat_benches BETWEEN 0 AND 999
            AND incline_benches BETWEEN 0 AND 999
            AND platforms BETWEEN 0 AND 999
            AND preacher_curl_stations BETWEEN 0 AND 999
        )
);

CREATE TABLE IF NOT EXISTS public.gym_free_weight_suggestions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id integer NOT NULL REFERENCES public.gyms(id) ON DELETE CASCADE,
    dumbbell_min_kg integer,
    dumbbell_max_kg integer,
    dumbbell_racks integer NOT NULL DEFAULT 0,
    squat_racks integer NOT NULL DEFAULT 0,
    flat_benches integer NOT NULL DEFAULT 0,
    incline_benches integer NOT NULL DEFAULT 0,
    platforms integer NOT NULL DEFAULT 0,
    preacher_curl_stations integer NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'pending',
    submitted_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT gym_free_weight_suggestions_status_check
        CHECK (status IN ('pending', 'approved', 'rejected')),
    CONSTRAINT gym_free_weight_suggestions_dumbbell_min_check
        CHECK (dumbbell_min_kg IS NULL OR dumbbell_min_kg BETWEEN 0 AND 999),
    CONSTRAINT gym_free_weight_suggestions_dumbbell_max_check
        CHECK (dumbbell_max_kg IS NULL OR dumbbell_max_kg BETWEEN 0 AND 999),
    CONSTRAINT gym_free_weight_suggestions_dumbbell_range_check
        CHECK (dumbbell_min_kg IS NULL OR dumbbell_max_kg IS NULL OR dumbbell_max_kg >= dumbbell_min_kg),
    CONSTRAINT gym_free_weight_suggestions_counts_check
        CHECK (
            dumbbell_racks BETWEEN 0 AND 999
            AND squat_racks BETWEEN 0 AND 999
            AND flat_benches BETWEEN 0 AND 999
            AND incline_benches BETWEEN 0 AND 999
            AND platforms BETWEEN 0 AND 999
            AND preacher_curl_stations BETWEEN 0 AND 999
        )
);

CREATE INDEX IF NOT EXISTS idx_gym_free_weight_suggestions_pending
    ON public.gym_free_weight_suggestions (created_at DESC)
    WHERE status = 'pending';

CREATE UNIQUE INDEX IF NOT EXISTS idx_gym_free_weight_suggestions_pending_user
    ON public.gym_free_weight_suggestions (gym_id, submitted_by)
    WHERE status = 'pending';

ALTER TABLE public.gym_free_weights ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gym_free_weight_suggestions ENABLE ROW LEVEL SECURITY;

COMMIT;
